### ISSUE TITLE
Server is not running

### ISSUE THREAD

**Issue by darwinDMG** [cweirup/JoplinSafariWebClipper#14]
Just installed the web clipper on an M1 Mac Studio, Safari 16.5, Ventura 13.4. I enabled the extension in the settings but it's showing as "Server not running!" when I try to clip something.

Is the server indeed still up or has it closed down?

**Comment by cweirup** [comment]
The Joplin app needs to be running for the clipper to work. The service runs with the app. I don't have a way around that; it's true of the official clipper as well. 

If Joplin is running, you'll want to confirm that you have the service started. Under Preferences -> Web Clipper, make sure the service is started under "Step 1: Enable the clipper service". I'm also assuming it is running on Port 41184, which Joplin should default to.

<img width="1256" alt="image" src="https://github.com/cweirup/JoplinSafariWebClipper/assets/216012/baef2e51-8ff1-453a-9710-ce033888ee7a">

**Comment by darwinDMG** [comment]
Got it! Thank you so much, this worked.

**Comment by cweirup** [comment]
Glad that worked! Thanks!
