### ISSUE TITLE
Some Clips are not possible

### ISSUE THREAD

**Issue by msman0** [cweirup/JoplinSafariWebClipper#15]
Hi! Clip URL is working but the other also simplified not. The system say "...processing" and nothing happens.
Is this a know issue? I have Joplin 2.12.19 on macOS.
Thank you.

**Comment by cweirup** [comment]
Appreciate your patience with my reply. Yes, I've seen this. If you have some examples, I'd appreciate you forwarding them.

From my initial investigation, it appears that it may be an issue with Joplin being able to process the site. I see the same behavior using the officially-supported Firefox extension, for example. 

I'm going to close this ticket and point you to a more recent one with similar issues., ticket #18.
