### ISSUE TITLE
Latest Safari 14 or latest Joplin this no longer allows picking folders

### ISSUE THREAD

**Issue by AddictArts** [cweirup/JoplinSafariWebClipper#4]
After updating the clipper says Joplin is running, but I can't select a folder. It will also no allow clipping, just disappears.

Any suggestions or ideas on what may have changed to stop it from working? Thanks for doing this project.

**Comment by bbchen** [comment]
Same here. I could not select folder using the latest Safari 14.

**Comment by JasonYangShadow** [comment]
yes, same here. Confirmed that folders and clipping do not work.

**Comment by cweirup** [comment]
Fix is coming. The issue has to do with a new API that Joplin introduced. I hope to have the extension updated in the next day or so.

**Comment by cweirup** [comment]
I just published a new release that should fix the API issues. Let me know if this works for you. 

[v0.2.0](https://github.com/cweirup/JoplinSafariWebClipper/releases/tag/v0.2.0)

**Comment by AddictArts** [comment]
Yes, fixed, thank you so much.
