### ISSUE TITLE
Notebook destination selection does not work

### ISSUE THREAD

**Issue by palijn** [cweirup/JoplinSafariWebClipper#5]
Hello,
On a vanilla installation of Joplin (Big Sur 11.2, Safari 14.0.3) the clipper always stores the note in the same notebook ("Folder" in the Clipper parlance), even if I select another one before clipping.
Notable maybe is that the folder used happens to be the first ever folder in this Joplin install, named "Welcome(Desktop)".

**Comment by leclercfl** [comment]
Actually, can't select the folder to save, and it does not save the note at all. Creating a default notebook such as Welcome, or Welcome (Desktop), or Folder does not help. 
Safari 14.0.3 on Mojave 10.14.6

**Comment by cweirup** [comment]
Which versions of the Clipper and Joplin are you using? If you are using Joplin prior to v1.4.12, you need to use Clipper v0.1.3. If you are using Joplin v1.4.12 or higher, you need to use Clipper v0.2.0.

I'm running it right now with Safari v14.0.3 on Big Sur 11.2 with Clipper v0.2.0 and Joplin v1.7.10 without issues. I can select Folders and it saves pages correctly.

**Comment by leclercfl** [comment]
OK, I was using Joplin 1.6.8 and Clipper 0.1, so I built the Clipper 0.2 and run it: I get the pop-up window but it's not added to the safari extension.

**Comment by cweirup** [comment]
Have you tried the pre-built release? https://github.com/cweirup/JoplinSafariWebClipper/releases/download/v0.2.0/Joplin.Clipper.zip

Can you see the extension in Safari's Extensions preference pane or it's not even there? I believe I've had some issues where the App Window loads, but it doesn't add to Safari (unless you clean the build folder).

**Comment by leclercfl** [comment]
Thanks. It works with the pre-built version 0.2.0. Great!

**Comment by cweirup** [comment]
Good news!

I thought about your issue with it not displaying when you built it. My guess is when you built it yourself, you needed to turn on "Allow Unsigned Extensions" from the Develop menu on Safari if it doesn't come up. If you don't sign it with Apple, Safari won't load it, even though the shell app runs. The pre-compiled version is signed.

**Comment by leclercfl** [comment]
OK, thanks for the tip about the unsigned extensions.
