### ISSUE TITLE
webclipper not working after joplin update

### ISSUE THREAD

**Issue by h0mesmart** [cweirup/JoplinSafariWebClipper#7]
Hey there,

After installing joplin v.2.1.7, the webclipper stopped working. impossible to launch the clipper. It's working before this version. I'm on safari 14.1.1. Thank you

**Comment by cweirup** [comment]
Yep, I’m aware of the issue. Joplin now requires the auth token in the API (seemed to be optional before v2). I’m working on the fix but will probably be a bit due to other commitments. If you need to use it with Joplin, I’d downgrade Joplin to 1.7 for now.

**Comment by h0mesmart** [comment]
thx for you message, indeed I've downgraded joplin. I don't know much about swift & co. but if you need help to test, I'm happy to help.

**Comment by cweirup** [comment]
I finally updated the Web Clipper to support the Authorization now required in Joplin V2.1.5 and later. Please test Clipper v0.2.1 and let me know if you are still experiencing issues. Thanks for your patience.

https://github.com/cweirup/JoplinSafariWebClipper/releases/tag/v0.2.1

**Comment by lclrc** [comment]
> [`v0.2.1` (release)](https://github.com/cweirup/JoplinSafariWebClipper/releases/tag/v0.2.1)

It works well with Joplin V2.3.5! Thanks for your work!

**Comment by cweirup** [comment]
@lclrc Thanks for the confirmation and the kind words!
