### ISSUE TITLE
Latest Big Sur Safari 14.1.1 the menu will not stay open when you click "J" in the toolbar

### ISSUE THREAD

**Issue by AddictArts** [cweirup/JoplinSafariWebClipper#8]
After upgrading to Big Sure the menu doesn't stay open, it shows up and disappears. Hopefully there is an easy solution. Thanks

**Comment by cweirup** [comment]
Which version of Joplin are you using? There is a known issue with v2+ that I'm working on.

**Comment by AddictArts** [comment]
I just noticed a new thing from using Firefox, Joplin had a prompt at the top to allow Firefox Joplin clipper. I think the Safari one is trying to "talk" to Joplin and is denied. It needs to do whatever it is to get the authorize or allow, then it would work I think.

**Comment by AddictArts** [comment]
Joplin 2.1.7 (prod, darwin)

Sync Version: 2
Profile Version: 39
Keychain Supported: Yes

Revision: 04c4015

**Comment by cweirup** [comment]
Yes, that is the issue. With the latest releases, Joplin has started enforcing "authentication" of the web clipper. Or more accurately, authentication with the underlying API. I'm working on incorporating that in my clipper, but need a few days. My solution will most likely start with having a customer enter their token that is generated in the app, but I'll see if I can also fit in the "allow clipper" functionality.

I'm already tracking this in Issue #7, so I'm going to close this issue out. Thanks!
