### ISSUE TITLE
Safari Extension requires to be granted permissions each time 

### ISSUE THREAD

**Issue by pnutster** [cweirup/JoplinSafariWebClipper#9]
Running Monterey - Safari: Version 15.3 (17612.4.9.1.5)
Joplin: Joplin 2.7.15 (prod, darwin)

Any time when Joplin is quit, and then opened again the Safari Extension requires to be granted Joplin Clipper authorization again.

Not entirely sure if you are still actively maintaining the Safari Clipper (I surely hope you do! Joplin is awesome!) Hopefully you can have a look at this. If you require any assistance, more info, more troubleshooting, screenshots, let me know and I will provide.

Thanks for the hard work on the Safari Clipper so far!

**Comment by cweirup** [comment]
Funny enough, I was looking at that this week with the Joplin API. I think I know how to fix it, but it will probably be a bit before I can finish it due to other commitments. I'll post again when I have a fix.

**Comment by cweirup** [comment]
@pnutster I finally got a chance to work on a fix and publish a new release. Let me know if this does or does not work to reduce how often you need to grant authorization.

https://github.com/cweirup/JoplinSafariWebClipper/releases/download/v0.3.0/Joplin-Clipper-v0.3.0.zip

**Comment by pnutster** [comment]
Hi Chris,

Thanks for working on this!

I did some testing, but can't get it to work at all!

created a short video: https://support.blueoceaninteractive.com//joplin-extension-optim <https://support.blueoceaninteractive.com//joplin-extension-optim>

Hope to hear from you soon.

With best regards,

Piet Nutbey

**Comment by cweirup** [comment]
Piet,

Thanks for sending the video. I'm not sure what's going on, as I'm not seeing it on my computer. 

Can you try try two things for me, if you haven't already?
1. Can you open a new tab or window, navigate to any random page (best if not in your browser cache), and see what happens?
2. Can you exit Safari then go back in and try the extension again (with Joplin running)?
 
Not sure these will solve it, but I've had issues in the past with the extension not loading properly with cached pages. 

Assuming that doesn't work, I might have to get a build out that has more logging turned on to see what's happening.

**Comment by cweirup** [comment]
I'm now able to recreate the problem, which appears to be with initial grant of permission.

You may want to go back to the previous version until I can get this cleaned up, as it may be a while. I'll probably also "unpublished" this build. 

Appreciate your patience with this.

**Comment by pnutster** [comment]
Fresh startup of system this morning. Fresh random, never visit page. Same thing, Joplin clipper opens up, and closes.

Perhaps an interesting fact, if I renew the Web Clipper token in Joplin, https://support.blueoceaninteractive.com//Shared-Image-2022-05-19-10-03-00 <https://support.blueoceaninteractive.com//Shared-Image-2022-05-19-10-03-00> - technically the Web Clipper needs to be granted permission again. WebClipper in both Chrome and FireFox need to be re-granted permission. It does not ask for re-granting permissions for the Safari WebClipper.

**Comment by jeffabailey** [comment]
I'm experiencing the same problem.

If there's a specific place to look in the code, I can try to fix it.

**Comment by cweirup** [comment]
@pnutster @jeffabailey  I just published a new build ([v.0.4.0](https://github.com/cweirup/JoplinSafariWebClipper/releases/tag/v0.4.0)) that I believe solves the authorization persistence issue. I'd appreciate if you could try it out. 

Thanks!
Chris

**Comment by jeffabailey** [comment]
It works.

**Comment by pnutster** [comment]
Works beautifully Chris!

Thanks for putting your time and effort into fixing this!

**Comment by cweirup** [comment]
Great to hear! Sorry it took so long.
